# Generated by Django 2.1.2 on 2018-10-20 10:27

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Launch',
            fields=[
                ('id', models.AutoField(help_text='Unique ID of launch event', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, help_text='Name of launch', max_length=100)),
                ('rocket', models.CharField(help_text='Name of rocket', max_length=100)),
                ('location', models.CharField(help_text='Location', max_length=100)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('lng', models.DecimalField(decimal_places=6, max_digits=9)),
            ],
        ),
    ]
