# Generated by Django 2.1.2 on 2018-10-21 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('launches', '0002_auto_20181020_2243'),
    ]

    operations = [
        migrations.AddField(
            model_name='launch',
            name='livestream',
            field=models.CharField(blank=True, help_text='Link to livestream', max_length=300),
        ),
    ]
