# Generated by Django 2.1.2 on 2018-10-20 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='port',
            name='viewpoints',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='port',
            name='website',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
