# Generated by Django 2.1.2 on 2018-10-20 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ports', '0002_auto_20181020_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='port',
            name='viewpoints',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
