# Generated by Django 2.1.2 on 2018-10-20 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ports', '0003_auto_20181020_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='port',
            name='lat',
            field=models.DecimalField(decimal_places=9, max_digits=9),
        ),
        migrations.AlterField(
            model_name='port',
            name='lng',
            field=models.DecimalField(decimal_places=9, max_digits=9),
        ),
    ]
