# Generated by Django 2.1.2 on 2018-10-20 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        migrations.AddField(
            model_name='user',
            name='is_spaceorg',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
